In [2]:
import os
import gzip
from collections import Counter
import ijson  # pip install ijson
import pandas as pd
from pathlib import Path

FILES = {
    'nif_context_en.ttl': 'nif_context_en.ttl',      # ~28G - training corpus
    'labels_en.ttl': 'labels_en.ttl',                # ~900M - 4.8M entities
    'instance_types_en.ttl': 'instance_types_en.ttl', # ~220M - typed entities
    'redirects_en.ttl': 'redirects_en.ttl'           # ~500M - normalization
}

base_dir = Path('../dbpedia-2016-10')
for f, path in FILES.items():
    full_path = base_dir / path
    print(f"\n{f}")
    print(f"size: {full_path.stat().st_size / 1e9:.2f} GB")
    print(f"lines: {sum(1 for _ in open(full_path)):,}")

nif_context_en.ttl
size: 20.41 GB
lines: 29,642,397

labels_en.ttl
size: 1.59 GB
lines: 12,845,254

instance_types_en.ttl
size: 0.75 GB
lines: 5,150,434

redirects_en.ttl
size: 1.18 GB
lines: 7,699,478

In [3]:
for f, path in FILES.items():
    print(f"\n {path}")
    with open(base_dir / path) as fp:
        for i, line in enumerate(fp):
            print(repr(line.rstrip()))
            if i >= 9: break

 nif_context_en.ttl
'# started 2017-02-07T14:14:05Z'
'<http://dbpedia.org/resource/Animalia_(book)?dbpv=2016-10&nif=context> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#Context> .'
'<http://dbpedia.org/resource/Animalia_(book)?dbpv=2016-10&nif=context> <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#beginIndex> "0"^^<http://www.w3.org/2001/XMLSchema#nonNegativeInteger> .'
'<http://dbpedia.org/resource/Animalia_(book)?dbpv=2016-10&nif=context> <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#endIndex> "2294"^^<http://www.w3.org/2001/XMLSchema#nonNegativeInteger> .'
'<http://dbpedia.org/resource/Animalia_(book)?dbpv=2016-10&nif=context> <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#sourceUrl> <http://en.wikipedia.org/wiki/Animalia_(book)?oldid=741600610> .'
'<http://dbpedia.org/resource/Animalia_(book)?dbpv=2016-10&nif=context> <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#isString> "Animalia is an illustrated children\'s book by Graeme Base. It was originally published in 1986, followed by a tenth anniversary edition in 1996, and a 25th anniversary edition in 2012. Over three million copies have been sold. A special numbered and signed anniversary edition was also published in 1996, with an embossed gold jacket.\\n\\nSynopsis\\nAnimalia is an alliterative alphabet book and contains twenty-six illustrations, one for each letter of the alphabet. Each illustration features an animal from the animal kingdom (A is for alligator, B is for butterfly, etc.) along with a short poem utilizing the letter of the page for many of the words. The illustrations contain many other objects beginning with that letter that the reader can try to identify. As an additional challenge, the author has hidden a picture of himself as a child in every picture.\\n\\nRelated products\\nJulia MacRae Books published an Animalia colouring book in 2008. H. N. Abrams also published a wall calendar colouring book version for children the same year. H. N. Abrams published The Animalia Wall Frieze, a fold-out over 26 feet in length, in which the author created new riddles for each letter. The Great American Puzzle Factory created a 300-piece jigsaw puzzle based on the book\'s cover.\\n\\nAdaptations\\nA television series was also created, based on the book, which airs in the United States, Australia, Canada, the United Kingdom, Norway and Venezuela. It also airs on Minimax for the Czech Republic and Slovakia. And recently in Greece on the channel ET1. The Australian Children\'s Television Foundation released a teaching resource DVD-ROM in 2011 to accompany the TV series with teaching aids for classroom use. In 2010, The Base Factory and AppBooks released Animalia as an application for iPad and iPhone/iPod Touch.\\n\\nAwards\\nAnimalia won the Young Australian\'s Best Book Award in 1987 for Best Picture Story Book. The Children\'s Book Council of Australia designated Animalia a 1987 Picture Book of the Year: Honour Book. Kid\'s Own Australian Literature Awards named Animalia the 1988 Picture Book Winner.\\n\\nReferences\\n\\n\\nExternal links\\n\\n*  Graeme Base\'s official website \\n*  Animalia The Television Series official website \\n*  A Learning Time activity guide for Animalia created by The Little Big Book Club" .'
'<http://dbpedia.org/resource/Animalia_(book)?dbpv=2016-10&nif=context> <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#predLang> <http://lexvo.org/id/iso639-3/eng> .'
'<http://dbpedia.org/resource/Actrius?dbpv=2016-10&nif=context> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#Context> .'
'<http://dbpedia.org/resource/Actrius?dbpv=2016-10&nif=context> <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#beginIndex> "0"^^<http://www.w3.org/2001/XMLSchema#nonNegativeInteger> .'
'<http://dbpedia.org/resource/Actrius?dbpv=2016-10&nif=context> <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#endIndex> "2462"^^<http://www.w3.org/2001/XMLSchema#nonNegativeInteger> .'

 labels_en.ttl
'# started 2017-03-14T08:38:43Z'
'<http://dbpedia.org/resource/AccessibleComputing> <http://www.w3.org/2000/01/rdf-schema#label> "AccessibleComputing"@en .'
'<http://dbpedia.org/resource/AfghanistanHistory> <http://www.w3.org/2000/01/rdf-schema#label> "AfghanistanHistory"@en .'
'<http://dbpedia.org/resource/AfghanistanGeography> <http://www.w3.org/2000/01/rdf-schema#label> "AfghanistanGeography"@en .'
'<http://dbpedia.org/resource/AfghanistanPeople> <http://www.w3.org/2000/01/rdf-schema#label> "AfghanistanPeople"@en .'
'<http://dbpedia.org/resource/AfghanistanCommunications> <http://www.w3.org/2000/01/rdf-schema#label> "AfghanistanCommunications"@en .'
'<http://dbpedia.org/resource/AfghanistanTransportations> <http://www.w3.org/2000/01/rdf-schema#label> "AfghanistanTransportations"@en .'
'<http://dbpedia.org/resource/AfghanistanMilitary> <http://www.w3.org/2000/01/rdf-schema#label> "AfghanistanMilitary"@en .'
'<http://dbpedia.org/resource/AfghanistanTransnationalIssues> <http://www.w3.org/2000/01/rdf-schema#label> "AfghanistanTransnationalIssues"@en .'
'<http://dbpedia.org/resource/AssistiveTechnology> <http://www.w3.org/2000/01/rdf-schema#label> "AssistiveTechnology"@en .'

 instance_types_en.ttl
'# started 2017-03-31T16:36:17Z'
'<http://dbpedia.org/resource/Anarchism> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#Thing> .'
'<http://dbpedia.org/resource/Achilles> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#Thing> .'
'<http://dbpedia.org/resource/Autism> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/Disease> .'
'<http://dbpedia.org/resource/Alabama> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/AdministrativeRegion> .'
'<http://dbpedia.org/resource/Abraham_Lincoln> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/OfficeHolder> .'
'<http://dbpedia.org/resource/Abraham_Lincoln__1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/TimePeriod> .'
'<http://dbpedia.org/resource/Abraham_Lincoln__2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/TimePeriod> .'
'<http://dbpedia.org/resource/Abraham_Lincoln__3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/TimePeriod> .'
'<http://dbpedia.org/resource/An_American_in_Paris> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#Thing> .'

 redirects_en.ttl
'# started 2017-03-14T08:38:43Z'
'<http://dbpedia.org/resource/AccessibleComputing> <http://dbpedia.org/ontology/wikiPageRedirects> <http://dbpedia.org/resource/Computer_accessibility> .'
'<http://dbpedia.org/resource/AfghanistanHistory> <http://dbpedia.org/ontology/wikiPageRedirects> <http://dbpedia.org/resource/History_of_Afghanistan> .'
'<http://dbpedia.org/resource/AfghanistanGeography> <http://dbpedia.org/ontology/wikiPageRedirects> <http://dbpedia.org/resource/Geography_of_Afghanistan> .'
'<http://dbpedia.org/resource/AfghanistanPeople> <http://dbpedia.org/ontology/wikiPageRedirects> <http://dbpedia.org/resource/Demographics_of_Afghanistan> .'
'<http://dbpedia.org/resource/AfghanistanCommunications> <http://dbpedia.org/ontology/wikiPageRedirects> <http://dbpedia.org/resource/Communications_in_Afghanistan> .'
'<http://dbpedia.org/resource/AfghanistanTransportations> <http://dbpedia.org/ontology/wikiPageRedirects> <http://dbpedia.org/resource/Transport_in_Afghanistan> .'
'<http://dbpedia.org/resource/AfghanistanMilitary> <http://dbpedia.org/ontology/wikiPageRedirects> <http://dbpedia.org/resource/Afghan_Armed_Forces> .'
'<http://dbpedia.org/resource/AfghanistanTransnationalIssues> <http://dbpedia.org/ontology/wikiPageRedirects> <http://dbpedia.org/resource/Foreign_relations_of_Afghanistan> .'
'<http://dbpedia.org/resource/AssistiveTechnology> <http://dbpedia.org/ontology/wikiPageRedirects> <http://dbpedia.org/resource/Assistive_technology> .'

In [4]:
def parse_ttl_sample(file_path, max_lines=1000):
    triples = []
    with open(file_path) as f:
        for i, line in enumerate(f):
            if i >= max_lines: break
            line = line.strip()
            if line and not line.startswith('#'):
                parts = [p.strip('<> "') for p in line.split() if p.strip()]
                if len(parts) >= 3:
                    triples.append((parts[0], parts[1], parts[2]))
    return pd.DataFrame(triples, columns=['subject', 'predicate', 'object'])

for f, path in FILES.items():
    df = parse_ttl_sample(base_dir / path)
    print(f"\n## {f} Structure (sample {len(df)} triples)")
    print(df['predicate'].value_counts().head())
    print("\nSample subjects:", df['subject'].str.startswith('http://dbpedia.org/resource/').sum(), f"/ {len(df)}")
    display(df.head(3))

## nif_context_en.ttl Structure (sample 999 triples)
predicate
http://www.w3.org/1999/02/22-rdf-syntax-ns#type                              167
http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#beginIndex    167
http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#predLang      167
http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#endIndex      166
http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#sourceUrl     166
Name: count, dtype: int64

Sample subjects: 999 / 999

,subject,predicate,object
0,http://dbpedia.org/resource/Animalia_(book)?db...,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,http://persistence.uni-leipzig.org/nlp2rdf/ont...
1,http://dbpedia.org/resource/Animalia_(book)?db...,http://persistence.uni-leipzig.org/nlp2rdf/ont...,"0""^^<http://www.w3.org/2001/XMLSchema#nonNegat..."
2,http://dbpedia.org/resource/Animalia_(book)?db...,http://persistence.uni-leipzig.org/nlp2rdf/ont...,"2294""^^<http://www.w3.org/2001/XMLSchema#nonNe..."

## labels_en.ttl Structure (sample 999 triples)
predicate
http://www.w3.org/2000/01/rdf-schema#label    999
Name: count, dtype: int64

Sample subjects: 999 / 999

,subject,predicate,object
0,http://dbpedia.org/resource/AccessibleComputing,http://www.w3.org/2000/01/rdf-schema#label,"AccessibleComputing""@en"
1,http://dbpedia.org/resource/AfghanistanHistory,http://www.w3.org/2000/01/rdf-schema#label,"AfghanistanHistory""@en"
2,http://dbpedia.org/resource/AfghanistanGeography,http://www.w3.org/2000/01/rdf-schema#label,"AfghanistanGeography""@en"

## instance_types_en.ttl Structure (sample 999 triples)
predicate
http://www.w3.org/1999/02/22-rdf-syntax-ns#type    999
Name: count, dtype: int64

Sample subjects: 999 / 999

,subject,predicate,object
0,http://dbpedia.org/resource/Anarchism,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,http://www.w3.org/2002/07/owl#Thing
1,http://dbpedia.org/resource/Achilles,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,http://www.w3.org/2002/07/owl#Thing
2,http://dbpedia.org/resource/Autism,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,http://dbpedia.org/ontology/Disease

## redirects_en.ttl Structure (sample 999 triples)
predicate
http://dbpedia.org/ontology/wikiPageRedirects    999
Name: count, dtype: int64

Sample subjects: 999 / 999

,subject,predicate,object
0,http://dbpedia.org/resource/AccessibleComputing,http://dbpedia.org/ontology/wikiPageRedirects,http://dbpedia.org/resource/Computer_accessibi...
1,http://dbpedia.org/resource/AfghanistanHistory,http://dbpedia.org/ontology/wikiPageRedirects,http://dbpedia.org/resource/History_of_Afghani...
2,http://dbpedia.org/resource/AfghanistanGeography,http://dbpedia.org/ontology/wikiPageRedirects,http://dbpedia.org/resource/Geography_of_Afgha...

In [5]:
import re

def count_dbpedia_resources(file_path):
    """Count unique http://dbpedia.org/resource/* subjects/objects"""
    resources = set()
    with open(file_path) as f:
        content = f.read()  # or stream for huge files
        matches = re.findall(r'http://dbpedia\.org/resource/[^<>\s"]+', content)
        return len(set(matches))

# SAFE streaming version (memory-efficient)
def stream_count_resources(file_path):
    resources = Counter()
    with open(file_path) as f:
        buffer = ''
        for line in f:
            buffer += line
            while '\n' in buffer:
                triple, buffer = buffer.split('\n', 1)
                if triple.strip() and not triple.startswith('#'):
                    matches = re.findall(r'http://dbpedia\.org/resource/[^<>\s"]+', triple)
                    for m in matches:
                        resources[m] += 1
    return len(resources)

print("LABELS (4.8M expected):")
labels_count = stream_count_resources(base_dir / 'labels_en.ttl')
print(f"Unique DBpedia resources: {labels_count:,}")

print("\nINSTANCE_TYPES (~4M expected):")
inst_count = stream_count_resources(base_dir / 'instance_types_en.ttl')
print(f"Unique DBpedia resources: {inst_count:,}")

LABELS (4.8M expected):
Unique DBpedia resources: 12,845,247

INSTANCE_TYPES (~4M expected):
Unique DBpedia resources: 5,044,223

In [ ]:
#!pip install gensim==3.4.0 doesnt work so we keep 4.4

import gensim
from gensim.models import Word2Vec
import re
import ijson
from pathlib import Path
from tqdm import tqdm
import pickle

nif_path = Path('nif_context_en.ttl')
sentences_file = 'sentences.pkl'  # Save tokenized corpus
model_file = 'joint_embeddings_200d.model'

Collecting gensim==3.4.0
  Downloading gensim-3.4.0.tar.gz (22.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.2/22.2 MB 8.7 MB/s eta 0:00:0000:0100:01m
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-1.3.2.tar.gz
      Extracting in /tmp/tmp5xuxhg9y
      Traceback (most recent call last):
        File "/tmp/pip-install-8e_6k0ih/gensim_65fb7d2ca28d482181ea316b59728578/ez_setup.py", line 136, in use_setuptools
          import pkg_resources
      ModuleNotFoundError: No module named 'pkg_resources'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/home/alant/myglobal/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/alant/myglobal/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/alant/myglobal/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-jd793z1_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-jd793z1_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-jd793z1_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 520, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-jd793z1_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
        File "<string>", line 23, in <module>
        File "/tmp/pip-install-8e_6k0ih/gensim_65fb7d2ca28d482181ea316b59728578/ez_setup.py", line 138, in use_setuptools
          return _do_download(version, download_base, to_dir, download_delay)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-8e_6k0ih/gensim_65fb7d2ca28d482181ea316b59728578/ez_setup.py", line 117, in _do_download
          _build_egg(egg, tarball, to_dir)
        File "/tmp/pip-install-8e_6k0ih/gensim_65fb7d2ca28d482181ea316b59728578/ez_setup.py", line 89, in _build_egg
          tar = tarfile.open(tarball)
                ^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/tarfile.py", line 1862, in open
          raise ReadError(f"file could not be opened successfully:\n{error_msgs_summary}")
      tarfile.ReadError: file could not be opened successfully:
      - method gz: ReadError('not a gzip file')
      - method bz2: ReadError('not a bzip2 file')
      - method xz: ReadError('not an lzma file')
      - method tar: ReadError('truncated header')
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.