# Exploration Testset

Exploring the format of the data and the files

In [ ]:
import numpy as np 
import cbor2 
from pathlib import Path
import pandas as pd 

base = Path.cwd() 
target = base / "../Testset/benchmarkY2test-auto-manual-qrels/benchmarkY2test"

!tree -L 1 {target}

/tempory/the_three_potatoes/ri_project/workspaces/amelie/RI_Project/Notebooks/../Testset/benchmarkY2test-auto-manual-qrels/benchmarkY2test
├── benchmarkY2test-entity-automatic.qrels
├── benchmarkY2test-entity-lenient.qrels
├── benchmarkY2test-entity-manual.qrels
├── benchmarkY2test-entity-with-passage-manual.qrels
├── benchmarkY2test-goldarticles.cbor
├── benchmarkY2test-goldpassages.cbor
├── benchmarkY2test-goldpassages.qrels
├── benchmarkY2test-psg-lenient.qrels
├── benchmarkY2test-psg-manual.qrels
├── interface.json
└── README.mkd

1 directory, 11 files

---
source : https://trec-car.cs.unh.edu/

The **TREC CAR Y2** has 2 tasks:
- passage ranking
- entity ranking 

The evaluation is as follow: given a query Q, for each of its sections (headers ?), retrieve a ranking of relevant entity-passage tuple (E, P).
Passage come from the corpus, entity is the entry to the knowledge base. 
We define a passage or entity as relevant if the passage content or entity should be mentioned in the knowledge article. Different degrees of “could be mentioned”, “should be mentioned”, or “must be mentioned” are represented through a graded annotation scale during manual assessment.

In the passage ranking task, entities are omitted.

In the entity ranking task, the entity must be given, and optionally, complemented with a passage that serves as provenance for why the entity is relevant. If the passage is omitted, it will be replaced with the first paragraph from the entity’s article.

---

Qrels files correspond to the annotations of the train and test data.
They follow this format

TOPIC |      ITERATION |      DOCUMENT# |      RELEVANCY |

where TOPIC is the topic number,

ITERATION is the feedback iteration (almost always zero and not used),

DOCUMENT# is the official document number that corresponds to the "docno" field in the documents, and

RELEVANCY is a binary code of 0 for not relevant and 1 for relevant.

---
We explore some of the files. As stated in the article, only the automatic judgement is considered.

#### benchmarkY2test-entity-automatic.qrels

In [ ]:
entity_auto_qrels = pd.read_csv(
    target / "benchmarkY2test-entity-automatic.qrels",
    sep=r"\s+",
    header=None,
    names=["query_id", "iteration", "doc_id", "relevance"]
)

entity_auto_qrels.drop(columns=['iteration'], inplace=True) # iteration is always 0, so we can drop it
entity_auto_qrels.head()

# for each query_id, the docs that are relevant

,query_id,doc_id,relevance
0,enwiki:Aerobic%20fermentation/Aerobic%20fermen...,enwiki:Lactic%20acid,1
1,enwiki:Aerobic%20fermentation/Aerobic%20fermen...,enwiki:Phenotype,1
2,enwiki:Aerobic%20fermentation/Aerobic%20fermen...,enwiki:Biological%20engineering,1
3,enwiki:Aerobic%20fermentation/Aerobic%20fermen...,enwiki:Cytochrome%20c%20oxidase,1
4,enwiki:Aerobic%20fermentation/Aerobic%20fermen...,enwiki:Redox,1

In [20]:
entity_auto_qrels.shape, entity_auto_qrels['relevance'].unique()

((17044, 3), array([1]))

In [28]:
entity_auto_qrels.head()['query_id'].unique(), entity_auto_qrels['query_id'].nunique()

(<StringArray>
 ['enwiki:Aerobic%20fermentation/Aerobic%20fermentation%20in%20non-yeast%20species']
 Length: 1, dtype: str,
 976)

#### benchmarkY2test-entity-lenient.qrels (not taken into account as not automatic)

In [23]:
entity_len_qrels = pd.read_csv(
    target / "benchmarkY2test-entity-lenient.qrels",
    sep=r"\s+",
    header=None,
    names=["query_id", "iteration", "doc_id", "relevance"]
)

entity_len_qrels.drop(columns=['iteration'], inplace=True) # iteration is always 0, so we can drop it
entity_len_qrels.head()

# for each query_id, the docs that are relevant

,query_id,doc_id,relevance
0,enwiki:Aerobic%20fermentation/Aerobic%20fermen...,enwiki:Anaerobic%20respiration,0
1,enwiki:Aerobic%20fermentation/Aerobic%20fermen...,enwiki:Biohydrogen,0
2,enwiki:Aerobic%20fermentation/Aerobic%20fermen...,enwiki:Carbon%20dioxide,2
3,enwiki:Aerobic%20fermentation/Aerobic%20fermen...,enwiki:Cellular%20respiration,2
4,enwiki:Aerobic%20fermentation/Aerobic%20fermen...,enwiki:Citric%20acid%20cycle,2

In [29]:
entity_len_qrels.shape, sorted(entity_len_qrels['relevance'].unique())

((8415, 3),
 [np.int64(-2),
  np.int64(0),
  np.int64(2),
  np.int64(3),
  np.int64(4),
  np.int64(5)])

In [27]:
entity_len_qrels.head()['query_id'].unique(), entity_len_qrels['query_id'].nunique()

(<StringArray>
 ['enwiki:Aerobic%20fermentation/Aerobic%20fermentation%20in%20non-yeast%20species/E.%20coli%20mutant']
 Length: 1, dtype: str,
 271)

#### benchmarkY2test-entity-with-passage-manual.qrels (not used)

In [30]:
tmp = pd.read_csv(
    target / "benchmarkY2test-entity-with-passage-manual.qrels",
    sep=r"\s+",
    header=None,
    names=["query_id", "iteration", "doc_id", "relevance"]
)

tmp.drop(columns=['iteration'], inplace=True) # iteration is always 0, so we can drop it
tmp.head()

# for each query_id, the docs that are relevant

,query_id,doc_id,relevance
0,enwiki:Aerobic%20fermentation/Aerobic%20fermen...,00de04a88d0f50387f488c9fb8f71ac24a4b0048/enwik...,0
1,enwiki:Aerobic%20fermentation/Aerobic%20fermen...,0ba471e24cf7b3aa7b129c9148fefc891c39e337/enwik...,-1
2,enwiki:Aerobic%20fermentation/Aerobic%20fermen...,1d18136a6764db7de09cabd4ef8a2852980ce275/enwik...,0
3,enwiki:Aerobic%20fermentation/Aerobic%20fermen...,20558c26a8282f9787de765f331c01df8b9a0ecc/enwik...,-1
4,enwiki:Aerobic%20fermentation/Aerobic%20fermen...,296f175bc90acda15321b5a91ef81a20e9faa5e1/enwik...,0

In [31]:
tmp.shape, sorted(tmp['relevance'].unique())

((11440, 3),
 [np.int64(-2),
  np.int64(-1),
  np.int64(0),
  np.int64(1),
  np.int64(2),
  np.int64(3)])

#### benchmarkY2test-goldpassages.qrels

In [ ]:
gold_psg_qrels = pd.read_csv(
    target / "benchmarkY2test-goldpassages.qrels",
    sep=r"\s+",
    header=None,
    names=["query_id", "iteration", "doc_id", "relevance"]
)

gold_psg_qrels.drop(columns=['iteration'], inplace=True) # iteration is always 0, so we can drop it
gold_psg_qrels.head()

# for each query_id, the passages that are relevant

,query_id,doc_id,relevance
0,enwiki:Aerobic%20fermentation/Aerobic%20fermen...,559480f166353af56ab3ba23397aa1f246425a0c,1
1,enwiki:Aerobic%20fermentation/Aerobic%20fermen...,6d7a5f2baf661a86cec7d56fc08e079e34868a42,1
2,enwiki:Aerobic%20fermentation/Aerobic%20fermen...,a9f022e5fddd42ede054fc5b9142d4b4586217f7,1
3,enwiki:Aerobic%20fermentation/Aerobic%20fermen...,f687899c8c33d513212a7d0d67a247d8e8917b80,1
4,enwiki:Aerobic%20fermentation/Aerobic%20fermen...,a9f022e5fddd42ede054fc5b9142d4b4586217f7,1

In [33]:
gold_psg_qrels.shape, sorted(gold_psg_qrels['relevance'].unique())

((3598, 3), [np.int64(1)])

In [34]:
gold_psg_qrels.head()['query_id'].unique(), gold_psg_qrels['query_id'].nunique()

(<StringArray>
 ['enwiki:Aerobic%20fermentation/Aerobic%20fermentation%20in%20non-yeast%20species', 'enwiki:Aerobic%20fermentation/Aerobic%20fermentation%20in%20non-yeast%20species/E.%20coli%20mutant']
 Length: 2, dtype: str,
 1002)

#### goldarticles.cbor

In [35]:
gold_art = []

with open(target / "benchmarkY2test-goldarticles.cbor", "rb") as f:
    for i in range(2): # only 2 objects !
        obj = cbor2.load(f)
        gold_art.append(obj)
        print(type(obj))
        print(obj)
        print("=" * 50)

<class 'list'>
['CAR', [0], [0, [[0, 'tqa', 'en-us', 'tqa', []], [0, 'enwiki', 'en-US', '20180601', []]], 'benchmarkY2test', [], []]]
==================================================
<class 'list'>

In [36]:
# forma first element
def parse_car_header(obj):
    return {
        "format": obj[0],             
        "version": obj[1][0],         
        "corpora": [
            {
                "id": x[1],
                "lang": x[2],
                "source": x[3]
            }
            for x in obj[2][1]
        ],
        "dataset": obj[2][2]
    }

parse_car_header(gold_art[0])

{'format': 'CAR',
 'version': 0,
 'corpora': [{'id': 'tqa', 'lang': 'en-us', 'source': 'tqa'},
  {'id': 'enwiki', 'lang': 'en-US', 'source': '20180601'}],
 'dataset': 'benchmarkY2test'}

In [42]:
gold_art[1][10]

[0,
 'renewable energy resources',
 b'tqa:renewable%20energy%20resources',
 [[0,
   'Biomass',
   b'Biomass',
   [[1,
     [0,
      b'757503345757400822',
      [[0,
        'Biomass is another renewable source of energy. Biomass includes wood, grains, and other plant materials or waste materials. People can burn wood directly for energy in the form of heat. Biomass can also be processed to make biofuel. Biofuel is a fairly new type of energy that is becoming more popular. Biomass is useful because it can be made liquid. This means that they can be used in cars and trucks. Some car engines can be powered by pure vegetable oil or even recycled vegetable oil. Sometimes the exhaust from these cars smells like French fries! By using biofuels, we can cut down on the amount of fossil fuel that we use. Because living plants take carbon dioxide out of the air, growing plants for biofuel can mean that we will put less of this gas into the air overall. This could help us do something about the problem of global warming. ']]]]]],
  [0,
   'Solar Energy',
   b'Solar%20Energy',
   [[1, [0, b'6792016191492553574', [[0, '']]]]]],
  [0,
   'Wind as a Resource',
   b'Wind%20as%20a%20Resource',
   [[1,
     [0,
      b'-1725299520724969612',
      [[0,
        'Wind power uses moving air as a source of energy. Some types of wind power have been around for a long time. People have used windmills to grind grain and pump water for hundreds of years. Sailing ships have depended on wind for millennia. Wind is now used to generate electricity. Moving air can make a turbine spin, just like moving water can. Moving air has kinetic energy. When wind hits the blades of the turbine, the kinetic energy makes the blades move. The turbine spins and creates electricity. ']]]]]],
  [0,
   'Geothermal Energy',
   b'Geothermal%20Energy',
   [[1,
     [0,
      b'4683290611146908331',
      [[0,
        'Geothermal energy comes the Earths internal heat. Hot springs and geysers are produced by water that is heated by magma or hot rock below the surface. At a geothermal power plant, engineers drill wells into the hot rocks. Hot water or steam may come up through the wells. Alternatively, water may be put down into the well to be heated. It then comes up. The hot water or steam makes a turbine spin. This makes electricity. ']]]]]],
  [0,
   'Hydropower Plants',
   b'Hydropower%20Plants',
   [[1,
     [0,
      b'8259081204683262294',
      [[0,
        'To harness water power, a stream must be dammed. Narrow valleys are the best for dams. While sitting in the reservoir behind the dam, the water has potential energy. Water is allowed to flow downhill into a large turbine. While flowing downhill, the water has kinetic energy. Kinetic energy makes the turbine spin. The turbine is connected to a generator, which makes electricity. ']]]]]],
  [0,
   'Wind Power Advantages and Disadvantages',
   b'Wind%20Power%20Advantages%20and%20Disadvantages',
   [[1,
     [0,
      b'-6188968072540778060',
      [[0,
        'Wind power has many advantages. It is clean: it does not release pollutants or carbon dioxide. It is plentiful almost everywhere. The technology to harness wind energy is being developed rapidly. Wind power also has problems. Wind does not blow all of the time, so wind energy must be stored for later use. Alternatively, another energy source needs to be available when the wind is not blowing. Wind turbines are expensive. They can wear out quickly. Finally, windmills are not welcomed by residents of some locations. They say that they are unattractive. Yet even with these problems, wind turbines are a competitive form of renewable energy. Many states are currently using wind power. Wind turbines are set up in mountain passes. This is common in California, where cool Pacific Ocean air is sucked across the passes and into the warmer inland valleys. ']]]]]],
  [0,
   'Geothermal Energy as a Resource',
   b'Geothermal%20Energy%20as%20a%20Resource',
   [[1,
     [0,
      b'5093692811243408761',
      [[0,
        'Because the hot water or steam can be used directly to make a turbine spin, geothermal energy can be used without processing. Geothermal energy is clean and safe. It is renewable. There will always be hot rocks and water can be pumped down into a well. There, the water can be heated again to make more steam. Geothermal energy is an excellent resource in some parts of the world. Iceland is gets about one fourth of its electricity from geothermal sources. In the United States, California leads all states in producing geothermal energy. Geothermal energy in California is concentrated in the northern part of the state. The largest plant is in the Geysers Geothermal Resource Area. Geothermal energy is not economical everywhere. Many parts of the world do not have underground sources of heat that are close enough to the surface for building geothermal power plants. ']]]]]],
  [0,
   'Benefits and Problems of Hydropower',
   b'Benefits%20and%20Problems%20of%20Hydropower',
   [[1,
     [0,
      b'516880994817140403',
      [[0,
        'Water power does not burn a fuel. So it causes less pollution than many other kinds of energy. Water power is also a renewable resource. Water keeps flowing downhill. Although we use some of the energy from this movement, we are not using up the water. Water power does have problems. A large dam stops a streams flow, which floods the land upstream. A beautiful location may be lost. People may be displaced. The dams and turbines also change the downstream environment. Fish and other living things may not be able to survive. Dams slow the release of silt. Downstream deltas retreat and beaches may be starved of sand. Seaside cities may become exposed to storms and rising sea levels. Tidal power stations may need to close off a narrow bay or estuary. Wave power plants must withstand coastal storms and the corrosion of seawater. ']]]]]],
  [0,
   'Water Power',
   b'Water%20Power',
   [[1,
     [0,
      b'-4544790700234157829',
      [[0,
        'Moving water has energy (Figure 5.10). That energy is used to make electricity. Hydroelectric power harnesses the energy of water moving down a stream. Hydropower is the most widely used form of renewable energy in the world. This abundant energy source provides almost one fifth of the worlds electricity. The energy of waves and tides can also be used to produce water power. At this time, wave and tidal power are rare. ']]]]]],
  [0,
   'Solar Power Plants',
   b'Solar%20Power%20Plants',
   [[1,
     [0,
      b'3254897533582232830',
      [[0,
        'Sunlight is turned into electricity at a solar power plant. These power plants use a large group of mirrors to focus sunlight on one place. This place is called a receiver (Figure 5.8). At the receiver, a liquid such as oil or water is heated to a high temperature. The liquid transfers its heat by conduction. In conduction, energy moves between two objects that are in contact. The higher temperature object transfers heat to the lower temperature object. For example, when you heat a pot of water on a stove top, energy moves from the pot to its metal handle by conduction. At a solar power plant, the energy conducted by the heated liquid is used to make electricity. ']]]]]],
  [0,
   'KQED Geothermal Heats Up',
   b'KQED%20Geothermal%20Heats%20Up',
   [[1,
     [0,
      b'-2594819517100916950',
      [[0,
        'Where Earths internal heat gets close to the surface, geothermal power is a clean source of energy. In California, The Geysers supplies energy for many nearby homes and businesses. Learn more at: http://science.kqed.org/ques MEDIA Click image to the left or use the URL below. URL: ']]]]]],
  [0,
   'Hydropower as a Resource',
   b'Hydropower%20as%20a%20Resource',
   [[1,
     [0,
      b'3307701091477654603',
      [[0,
        'Many of the suitable streams in the United States have been developed for hydroelectric power. Many streams worldwide also have hydroelectric plants. Hydropower is a major source of Californias electricity. It accounts for about 14.5 percent of the total. Most of Californias nearly 400 hydroelectric power plants are located in the Sierra Nevada mountains. ']]]]]],
  [0,
   'Consequences of Solar Energy Use',
   b'Consequences%20of%20Solar%20Energy%20Use',
   [[1,
     [0,
      b'1805777608775009447',
      [[0,
        'Solar energy has many benefits. It does not produce any pollution. There is plenty of it available, much more than we could possibly use. But solar energy has problems. The Sun doesnt shine at night. A special battery is needed to store extra energy during the day for use at night. The technology for most uses of solar energy is still expensive. Until solar technology becomes more affordable, most people will prefer to get their energy from other sources. ']]]]]],
  [0,
   'Solar Energy as a Resource',
   b'Solar%20Energy%20as%20a%20Resource',
   [[1,
     [0,
      b'7863335913295642356',
      [[0,
        'Solar energy has been used on a small scale for hundreds of years. Today we are using solar energy for more of our power demands. Solar power plants are being built in many locations around the world. In the United States, the southwestern deserts are well suited for solar plants. ']]]]]],
  [0,
   'KQED Harnessing Power from the Sea',
   b'KQED%20Harnessing%20Power%20from%20the%20Sea',
   [[1,
     [0,
      b'-476740163605413069',
      [[0,
        'Although not yet widely used, many believe tidal power has more potential than wind or solar power for meeting alternative energy needs. Quest radio looks at plans for harnessing power from the sea by San Francisco and along the northern California coast. Learn more at: http://science.kqed.org/quest/audio/harnessing-power-from-the-sea/ MEDIA Click image to the left or use the URL below. URL: ']]]]]],
  [0,
   'Solar Energy Use',
   b'Solar%20Energy%20Use',
   [[1,
     [0,
      b'-7070687884990926142',
      [[0,
        'Solar energy is used to heat homes and water, and to make electricity. Scientists and engineers have many ways to get energy from the Sun (Figure 5.9). One is by using solar cells. Solar cells are devices that turn sunlight directly into electricity. Lots of solar cells make up an individual solar panel. You may have seen solar panels on roof tops. The Suns heat can also be trapped in your home by using south facing windows and good insulation. ']]]]]],
  [0,
   'Energy from the Sun',
   b'Energy%20from%20the%20Sun',
   [[1,
     [0,
      b'2486740352460699768',
      [[0,
        'The Sun is Earths main source of energy. The Sun gives us both light and heat. The Sun changes hydrogen into helium through nuclear fusion. This releases huge amounts of energy. The energy travels to the Earth mostly as visible light. The energy is carried through the empty space by radiation. We can use sunlight as an energy resource, called solar energy (Figure 5.7). ']]]]]],
  [0,
   'Wind Power',
   b'Wind%20Power',
   [[1,
     [0,
      b'7086957740752243840',
      [[0,
        'The energy from the Sun creates wind (Figure 5.11). Wind energy moves by convection. The Sun heats some locations more than others. Warm air rises, so other air rushes in to fill the hole left by the rising air. This horizontal movement of air is called wind. ']]]]]]],
 [0],
 []]

In [37]:
def parse_topic(node):
    """
    Recursively parse CAR topic tree
    """
    level = node[0]
    title = node[1]
    topic_id = node[2].decode("utf-8") if isinstance(node[2], bytes) else node[2]

    children = []

    # node[3] contains subtopics
    for child in node[3]:
        children.append(parse_topic(child))

    return {
        "level": level,
        "title": title,
        "id": topic_id,
        "children": children
    }

def parse_all_topics(raw_topics):
    return [parse_topic(t) for t in raw_topics]

In [38]:
topics_clean = parse_all_topics(gold_art[1])  # second list item
topics_clean

IndexError: list index out of range

#### goldpassage.cbor

In [45]:
gold_passages = []

with open(target / "benchmarkY2test-goldpassages.cbor", "rb") as f:
    for i in range(2): # only 2 objects !
        obj = cbor2.load(f)
        gold_passages.append(obj)
        print(type(obj))
        print(obj)
        print("=" * 50)

<class 'list'>
['CAR', [2], [0, [[0, 'tqa', 'en-us', 'tqa', []], [0, 'enwiki', 'en-US', '20180601', []]], 'benchmarkY2test', [], []]]
==================================================
<class 'list'>

In [46]:
parse_car_header(gold_passages[0])

{'format': 'CAR',
 'version': 2,
 'corpora': [{'id': 'tqa', 'lang': 'en-us', 'source': 'tqa'},
  {'id': 'enwiki', 'lang': 'en-US', 'source': '20180601'}],
 'dataset': 'benchmarkY2test'}